AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  snortai

  Backend service for the SnortAI application.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  SnortAiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        ProxyApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
    Metadata:
      BuildMethod: python3.11

  GenerateAndIndexAlertsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda_generate_and_index.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

Outputs:
  SnortApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/" 